reference = "REPLACEME" # Invoice Number, will be replaced
date = "REPLACEME" # Date of issue, will be replaced by local date on build

locale = "fr-CA"
currency = "CAD"
prepaid = 50 # Amount already paid by the client
tax = 5 # VAT in percent

[client]
  name = "Client name"
  address = ["line 1", "line 2", "COUNTRY"]
  other_info = ["optional other info", "other info line 2"]

[[TERMS]]
  TEXT = ["Lign 1 of footer terms", "Lign 2 of footer terms"]

[[line]]
  description = "item description"
  unitPrice = 100 # or hour rate, excl. VAT
  quantity = 3

[[line]]
  description = "item description #2"
  unitPrice = 500 # or hour rate, excl. VAT
  quantity = 2

[[line]]
  description = "item description #3"
  unitPrice = 250 # or hour rate, excl. VAT
  quantity = 1
