reference = "00000" # Invoice Number
date = 2020-01-01 # Date of issue

currency = ""
prepaid = 0 # Amount already paid by the client

[client]
  name = ""
  address = ["line 1", "line 2"]

[[line]]
  description = "item description"
  unit_price = 0 # or hour rate
  quantity = 1
